---
plugin: aws_ec2

strict_permissions: false

regions:
  - us-east-1
  - us-east-2
  - us-west-1

keyed_groups:
  - prefix: tower_role
    key: tags.TowerRole
  - prefix: tower_cluster
    key: tags.TowerClusterNameVerbose
  - prefiex: tower_database
    key: tags.TowerDatabase

groups:
  tower_nodes: tags.TowerRole in ['tower']
  database_nodes: tags.TowerRole in ['database']
