---
plugin: aws_ec2

strict_permissions: false

regions:
  - us-east-1
  - us-east-2
  - us-west-1

keyed_groups:
  - prefix: tower_role
    key: tags.TowerRole
  - prefix: tower_cluster
    key: tags.TowerClusterNameVerbose

groups:
  tower_nodes: tags.TowerRole in ['tower', 'database']
