---
- name: Create Host A
  delegate_to: localhost
  ec2:
    assign_public_ip: true
    ebs_optimized: true
    instance_tags: '{"key":"Name","key":"{{cluster_name}-hosta"}'
    instance_initiated_shutdown_behavior: "terminate"
    key_name: "{{ ec2_key_name }}"
    region: "{{ aws_region }}"
    zone: "{{ hosta_zone }}"
    group_id: "{{ hosta_security_group }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ami }}"
    wait: true
    count: 1
    vpc_subnet_id: "{{ hosta_subnet }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: "{{ root_fs_sc }}"
        volume_size: "{{ root_fs_size }}"
        delete_on_termination: true
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
  register: ec2_hosta_instance

- name: Create Host B
  delegate_to: localhost
  ec2:
    assign_public_ip: true
    ebs_optimized: true
    instance_tags: '{"key":"Name","key":"{{cluster_name}-hostb"}'
    instance_initiated_shutdown_behavior: "terminate"
    key_name: "{{ ec2_key_name }}"
    region: "{{ aws_region }}"
    zone: "{{ hostb_zone }}"
    group_id: "{{ hostb_security_group }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ami }}"
    wait: true
    count: 1
    vpc_subnet_id: "{{ hostb_subnet }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: "{{ root_fs_sc }}"
        volume_size: "{{ root_fs_size }}"
        delete_on_termination: true
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
  register: ec2_hostb_instance

- name: Create Host C
  delegate_to: localhost
  ec2:
    assign_public_ip: true
    ebs_optimized: true
    instance_tags: '{"key":"Name","key":"{{cluster_name}-hostc"}'
    instance_initiated_shutdown_behavior: "terminate"
    key_name: "{{ ec2_key_name }}"
    region: "{{ aws_region }}"
    zone: "{{ hostc_zone }}"
    group_id: "{{ hostc_security_group }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ami }}"
    wait: true
    count: 1
    vpc_subnet_id: "{{ hostc_subnet }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: "{{ root_fs_sc }}"
        volume_size: "{{ root_fs_size }}"
        delete_on_termination: true
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
  register: ec2_hostc_instance

# Create an in memory inventory of the tower cluster
- name: Add host facts for host A
  add_host:
    name: "{{cluster_name}}-tower-cluster-hosta"
    ansible_host: "{{ ec2_hosta_instance['instances'][0]['public_dns_name'] }}"
    ansible_ssh_private_key_file: "{{ ec2_key_file }}"
    ansible_user: ec2-user
    groups: "{{cluster_name}}-tower-cluster"

- name: Add host facts for host B
  add_host:
    name: "{{cluster_name}}-tower-cluster-hostb"
    ansible_host: "{{ ec2_hostb_instance['instances'][0]['public_dns_name'] }}"
    ansible_ssh_private_key_file: "{{ ec2_key_file }}"
    ansible_user: ec2-user
    groups: "{{cluster_name}}-tower-cluster"

- name: Add host facts for host C
  add_host:
    name: "{{cluster_name}}-tower-cluster-hostc"
    ansible_host: "{{ ec2_hostc_instance['instances'][0]['public_dns_name'] }}"
    ansible_ssh_private_key_file: "{{ ec2_key_file }}"
    ansible_user: ec2-user
    groups: "{{cluster_name}}-tower-cluster"

