---

- name: Download and unarchive tower installer
  delegate_to: localhost
  become: false
  unarchive:
    src: "https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{ tower_version }}.tar.gz"
    dest: /tmp/
    creates: "/tmp/ansible-tower-setup-{{ tower_version }}"
    remote_src: true

- name: Create inventory for tower
  template:
    src: 'inventory.j2'
    dest: '/tmp/ansible-tower-setup-{{ tower_version }}/inventory'
    mode: '0644'

#- name: Deploy Tower Cluster
#  delegate_to: localhost
#  become: false
#  command: setup.sh
#  args:
#    chdir: "/tmp/ansible-tower-setup-{{ tower_version }}"
