---

- name: Create tower instance(s)
  ec2:
    region: "{{ aws_region }}"
    instance_type: "{{ ec2_instance_type_tower }}"
    image: "{{ ec2_ami_ids[aws_region][ec2_ami_type] }}"
    key_name: "{{ ec2_key_name }}"
    user_data: "{{ lookup('template', 'user_data/tower.yml.j2') }}"
    vpc_subnet_id: "{{ ec2_public_subnet_id }}"
    group_id:
      - "{{ ec2_create_security_group_ssh.group_id }}"
      - "{{ ec2_create_security_group_cluster.group_id }}"
      - "{{ ec2_create_security_group_tower.group_id }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2_volume_size_tower_root }}"
        delete_on_termination: true
    instance_tags:
      TowerClusterName: "{{ cluster_name }}"
      TowerClusterNameVerbose: "{{ cluster_name_verbose }}"
      TowerRole: tower
    exact_count: "{{ tower_node_count }}"
    count_tag:
      TowerClusterName: "{{ cluster_name }}"
      TowerClusterNameVerbose: "{{ cluster_name_verbose }}"
      TowerRole: tower
    wait: true
  register: ec2_create_tower_instances

- name: Get list of tower instance(s) IDs
  set_fact:
    ec2_create_tower_instance_ids: "{{ ec2_create_tower_instances.tagged_instances | map(attribute='id') | list | sort }}"

- name: Tag tower instance(s)
  ec2_tag:
    region: "{{ aws_region }}"
    resource: "{{ item }}"
    tags:
      Name: "{{ cluster_name_verbose }}-tower{{ '%02d' | format(idx + 1) }}"
    state: present
  loop: "{{ ec2_create_tower_instance_ids }}"
  loop_control:
    index_var: idx

#- name: Tag first tower instance as the bastion
#  ec2_tag:
#    region: "{{ aws_region }}"
#    resource: "{{ ec2_create_tower_instance_ids[0] }}"
#    tags:
#      OpenShiftBastion: "true"
#    state: present

- name: Create database instance(s)
  ec2:
    region: "{{ aws_region }}"
    instance_type: "{{ ec2_instance_type_database }}"
    image: "{{ ec2_ami_ids[aws_region][ec2_ami_type] }}"
    key_name: "{{ ec2_key_name }}"
    user_data: "{{ lookup('file', 'user_data/database.yml') }}"
    vpc_subnet_id: "{{ ec2_public_subnet_id }}"
    group_id:
      - "{{ ec2_create_security_group_ssh.group_id }}"
      - "{{ ec2_create_security_group_cluster.group_id }}"
      - "{{ ec2_create_security_group_database.group_id }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2_volume_size_database_root }}"
        delete_on_termination: true
      - device_name: /dev/xvdb
        volume_type: gp2
        volume_size: "{{ ec2_volume_size_cns }}"
        delete_on_termination: true
    instance_tags:
      TowerClusterName: "{{ cluster_name }}"
      TowerClusterNameVerbose: "{{ cluster_name_verbose }}"
      TowerRole: database
    exact_count: "{{ database_node_count }}"
    count_tag:
      TowerClusterName: "{{ cluster_name }}"
      TowerClusterNameVerbose: "{{ cluster_name_verbose }}"
      TowerRole: database
    wait: true
  register: ec2_create_database_instances

- name: Get list of database instance(s) IDs
  set_fact:
    ec2_create_database_instance_ids: "{{ ec2_create_database_instances.tagged_instances | map(attribute='id') | list | sort }}"

- name: Tag database instance(s)
  ec2_tag:
    region: "{{ aws_region }}"
    resource: "{{ item }}"
    tags:
      Name: "{{ cluster_name_verbose }}-database{{ '%02d' | format(idx + 1) }}"
    state: present
  loop: "{{ ec2_create_database_instance_ids }}"
  loop_control:
    index_var: idx

# NOTE: The _odd_ syntax for the tags is due to needing to have
# a variable name in the tag key.
- name: Add Kubernetes cluster tag to instances
  ec2_tag:
    region: "{{ aws_region }}"
    resource: "{{ item }}"
    tags: "{
      'tower.io/cluster/{{ cluster_name_verbose }}': '{{ cluster_name_verbose }}'
    }"
    state: present
  with_items:
    - "{{ ec2_create_tower_instance_ids }}"
    - "{{ ec2_create_database_instance_ids }}"

- name: Create elastic IP for tower instance
  ec2_eip:
    device_id: "{{ ec2_create_tower_instance_ids[0] }}"
    region: "{{ aws_region }}"
    state: present
    in_vpc: true
  when: ec2_create_tower_instance_ids | length == 1

- name: Create elastic IP for database instance
  ec2_eip:
    device_id: "{{ ec2_create_database_instance_ids[0] }}"
    region: "{{ aws_region }}"
    state: present
    in_vpc: true
  when: ec2_create_database_instance_ids | length == 1
