---
- name: Find security groups
  ec2_group_facts:
    region: "{{ aws_region }}"
    filters:
      tag:TowerClusterName: "{{ cluster_name }}"
      tag:TowerClusterNameVerbose: "{{ cluster_name_verbose }}"
  register: ec2_find_security_groups

- name: Delete security groups
  ec2_group:
    group_id: "{{ item.group_id }}"
    region: "{{ aws_region }}"
    state: absent
  with_items: "{{ ec2_find_security_groups.security_groups }}"
